# Use root/example as user/password credentials

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8032:8080

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  mefit-backend:
    build: .
    depends_on:
      db:
        condition: service_started
    ports:
      - 3482:3482
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}