# Use root/example as user/password credentials
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8032:8080

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"

  mefit-backend:
    build: .
    depends_on:
      db:
        condition: service_started
    ports:
      - 3482:3482
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    # network_mode: "host"
  
  # rembg:
    # image: danielgatis/rembg
    # ports:
      # - "7000:7000"
    # command: s --host 0.0.0.0 --port 7000 --log_level info
  
  # ngrok:
    # image: ngrok/ngrok:latest
    # network_mode: host
    # environment:
      # - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    # command: http --url=antelope-able-hardly.ngrok-free.app 3482
  
  # oot-diffusion:
    # image: registry.hf.space/levihsu-ootdiffusion:latest
    # platform: linux/amd64
    # deploy:
      # resources:
        # reservations:
          # devices:
            # - driver: nvidia
              # count: all
              # capabilities: [gpu]
    # ports:
      # - "7860:7860"
    # command: python ./run/gradio_ootd.py